name: Build & Update Manifest

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Application Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_URI="ghcr.io/${{ github.repository_owner }}/hello-app:${{ github.sha }}"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Checkout Manifest Repository
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository_owner }}/hello-manifests'
          token: ${{ secrets.MANIFEST_REPO_PAT }}
          path: 'hello-manifests'

      - name: Update Deployment Image Tag
        run: |
          cd hello-manifests
          sed -i "s|image: ghcr.io/.*|image: ghcr.io/${{ github.repository_owner }}/hello-app:${{ github.sha }}|g" deployment.yaml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add deployment.yaml
          git commit -m "Update image tag to ${{ github.sha }}" || exit 0
          git push origin main